# Read the documentation: https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/index.md
oneup_uploader:
    mappings:
        medium:
            use_orphanage: true
            frontend: fineuploader
            storage:
                directory: "%kernel.root_dir%/../public"
            namer: App\Uploader\MediumNamer
            max_size: 2m
        attachable:
            use_orphanage: true
            frontend: fineuploader
            storage:
                directory: "%kernel.root_dir%/../public"
            max_size: 2m