security:
    encoders:
        AppBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_SALES:       ROLE_USER
        ROLE_CLERK:       ROLE_SALES
        ROLE_OWNER:       ROLE_CLERK
        ROLE_SUPER_ADMIN:
          - ROLE_OWNER
          - ROLE_ALLOWED_TO_SWITCH
          - ROLE_SONATA_ADMIN


    providers:
        user_provider:
            id: user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        admin:
            pattern:                  ^/(en/)?admin
            form_login:
                provider:             user_provider
                check_path:           admin_login_check
                login_path:           admin_login
                default_target_path:  sonata_admin_dashboard
                use_referer:          true
            logout:
                path:                 admin_logout
                target:               admin_login
            anonymous:                true
            switch_user:              true

        main:
            pattern: ^/
            form_login:
                provider: user_provider
                use_referer: true
                remember_me: true
                login_path: login
            remember_me:
                secret:   "%secret%"
                lifetime: 31536000
                path:     /
                domain:   ~
            logout:
                path:     logout
                target:   login
            anonymous:    true
            switch_user:  true

    access_control:
        - { path: ^/((en|it)/)?admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/((en|it)/)?admin/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/((en|it)/)?admin/, role: ROLE_SUPER_ADMIN }

        - { path: ^/(it/)?login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(it/)?register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(it/)?reset-password, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(it/)?content, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(it/)?customers, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/(it/)?documents/\d+/render, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(it/)?documents, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/(it/)?quotes, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/(it/)?invites/\.+/token, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(it/)?media, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/(it/)?pages, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/(it/)?paragraph-templates, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/(it/)?profile, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/(it/)?users, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/(it/)?working-notes, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^$(it/)?, role: IS_AUTHENTICATED_ANONYMOUSLY }
