vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/centos7-x64
                box_url: puphpet/centos7-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_3p3ne1x8nhth:
                        id: invox
                        hostname: invox.local
                        network:
                            private_network: 100.0.0.112
                            forwarded_port:
                                vflmnfp_edg46nqi46xt:
                                    host: '5254'
                                    guest: '22'
                        memory: '4096'
                        cpus: '4'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_vmzqskn7v0ay:
                source: ../
                target: /var/www/vhosts
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: vagrant
                group: vagrant
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - vim-common
        - htop
        - npm
        - vim-enhanced
        - java-1.8.0-openjdk
        - firefox
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
            - it_IT.UTF-8
        timezone: Europe/Rome
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        invox.local:
            server_name: invox.local
            www_root: /var/www/vhosts/main/web
            listen_port: '80'
            index_files:
                - app_dev.php
                - app.php
                - app_test.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_mc114fhtjwok:
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - /app.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_tvo2y2dpycdv:
                    location: '~ ^(.*)/(app|app_dev|app_test|config|phpinfo|index)\.php(/|$)'
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'SYMFONY_CACHE_DIR /dev/shm/cache'
                        - 'SYMFONY_LOGS_DIR /dev/shm/logs'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '0'
letsencrypt:
    install: '0'
php:
    install: '1'
    settings:
        version: '5.6'
    modules:
        php:
            - cli
            - intl
            - xml
            - imagick
            - mcrypt
            - mbstring
            - zip
            - gd
            - posix
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: Europe/Rome
        memory_limit: '-1'
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_e8fno9we5pef:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: vagrant
                group: vagrant
    composer: '1'
    composer_home: ''
xdebug:
    install: '0'
blackfire:
    install: '0'
xhprof:
    install: '0'
wpcli:
    install: '0'
drush:
    install: '0'
ruby:
    install: '1'
    versions:
        rv_47k0oncsfcew:
            default: '1'
            bundler: '1'
            version: 2.3.1
            gems:
                - deep_merge@1.0.1
                - activesupport@4.2.6
                - vine@0.2
                - sass
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    settings:
        version: '6'
    npm_packages:
        - bower
        - grunt
        - grunt-cli
        - less
        - uglify-js
        - uglifycss
hhvm:
    install: '0'
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: root
        override_options: {  }
    adminer: 0
    users: {  }
    databases:
        mariadbnd_lg2015a6lscr:
            name: db_dev
            sql: ''
        mariadbnd_0i1i53adxjg7:
            name: db_test
            sql: ''
        mariadbnd_nnqu33urzfpk:
            name: db_prod
            sql: ''
    grants: {  }
mysql:
    install: '1'
    settings:
        version: '5.7'
        root_password: 'root'
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_15nyjjgyuxr0:
            name: admin
            password: 'secret'
    databases:
        mysqlnd_lg2015a6lscr:
            name: db_dev
            sql: ''
        mysqlnd_0i1i53adxjg7:
            name: db_test
            sql: ''
        mysqlnd_nnqu33urzfpk:
            name: db_prod
            sql: ''
    grants:
        mysqlng_5z9zuvo5ffld:
            user: admin
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
mongodb:
    install: '0'
redis:
    install: '0'
sqlite:
    install: '1'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
beanstalkd:
    install: '0'
rabbitmq:
    install: '0'
elastic_search:
    install: '0'
solr:
    install: '0'
