# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    enable_analytics: true
    enable_chat: false
    enable_registration: true
    enable_homepage: true
    enable_fork_me: false
    enable_demo_mode: false
    demo_credentials:
        owner:
            email: demo.owner@invox.it
            password: demo
        manager:
            email: demo.manager@invox.it
            password: demo
        accountant:
            email: demo.accountant@invox.it
            password: demo
        sales_agent:
            email: demo.sales@invox.it
            password: demo

    launcher_links:
        demo: 'http://demo.invox.it/login'
        download_code: 'https://github.com/disider/invox/releases'
        wiki: 'https://github.com/disider/invox/wiki'
        github_repo: 'https://github.com/disider/invox'
        community: '#'
        join_development: 'https://github.com/disider/invox/fork'

    version: v0.2.19
    page_size: 25
    locale: 'en'
    available_locales:
        - en
        - it
    mailer.emails:
        no-reply: '%noreply_email%'
        info: '%info_email%'

    mailer.display_names:
        no-reply: '%noreply_display_name%'
        info: '%info_display_name%'

    noreply_display_name: 'No Reply'
    noreply_email: noreply@invox.it
    info_display_name: 'Invox - Info'
    info_email: info@invox.it

    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy
    loco_api_key: '%env(LOCO_API_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php,AppBundle,AdminBundle,Application}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Repository\CityRepository: ~

    # TODO: remove after migration to 4.x
    AppBundle\:
        resource: '../src/AppBundle/*'
        exclude: '../src/AppBundle/{Entity,Entity\Repository,Form\Processor,Migrations,Tests}'

    AppBundle\Controller\:
        arguments:
            $defaultPageSize: '%page_size%'
            $environment: '%kernel.environment%'
        resource: '../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']
    # End of "remove after migration to 4.x"

    AppBundle\EventListener\ORM\:
        resource: '../src/AppBundle/EventListener/ORM'
        tags: ['doctrine.event_subscriber']

    AppBundle\Form\Type\CountryEntityType:
        $locale: '%locale%'

    AppBundle\Model\LocaleFormatter:
        $locale: '%locale%'

    AppBundle\Twig\GlobalExtension:
        $debug: '%kernel.debug%'

    AppBundle\Entity\Manager\UserManager:
        arguments:
            $class: 'AppBundle\Entity\User'

    Twig_Extensions_Extension_Text:
        class: Twig_Extensions_Extension_Text

    AppBundle\Form\Processor\DocumentFormProcessor:
        arguments:
            $availableLocales: '%available_locales%'

    AppBundle\Mailer\Mailer:
        arguments:
            $displayNames: '%mailer.display_names%'
            $emails: '%mailer.emails%'

    AppBundle\Mailer\MailerInterface: '@AppBundle\Mailer\Mailer'

    AppBundle\Helper\ParameterHelperInterface: '@AppBundle\Helper\ParameterHelper'

    AppBundle\Builder\DocumentBuilder:
        arguments:
            $cacheDir: '%kernel.cache_dir%'

    AppBundle\Helper\ParameterHelper:
        arguments:
            - '%enable_demo_mode%'

    AppBundle\Pagination\DirectorySubscriber:
        tags:
            - { name: 'knp_paginator.subscriber' }

    AppBundle\Menu\MenuBuilder:
        arguments:
            $availableLocales: '%available_locales%'
            $locale: '%locale%'
            $enableRegistration: '%enable_registration%'
        tags:
            - { name: knp_menu.menu_builder, method: userMenu, alias: userMenu }
            - { name: knp_menu.menu_builder, method: mainMenu, alias: mainMenu }
            - { name: knp_menu.menu_builder, method: superadminMenu, alias: superadminMenu }

    AppBundle\Entity\Manager\CompanyManager:
        public: true
        arguments:
            - '@AppBundle\Repository\CompanyRepository'
            - '@security.token_storage'
            - '@session'

    Symfony\Component\HttpKernel\Profiler\Profiler: '@profiler'

    Oneup\UploaderBundle\Uploader\Orphanage\OrphanageManager: '@oneup_uploader.orphanage_manager'

